/* AccentNinja Corpus
 * CORPUS, MINIMAL_PAIRS, PHONEME_TIPS — pronunciation training data.
 *
 * Schema (full definition in Part 3 spec):
 *
 * CORPUS[levelNumber] = {
 *   name: string,
 *   nameEn: string,
 *   description: string,
 *   focus: string[],           // phoneme targets for this level
 *   items: CorpusItem[],
 * }
 *
 * CorpusItem = {
 *   id: string,
 *   type: 'word' | 'phrase' | 'sentence',
 *   text: string,              // English text to pronounce
 *   ipa: string,               // IPA transcription
 *   translation: string,       // French translation
 *   difficulty: 1..10,
 *   focusPhonemes: string[],   // IPA phonemes this item targets
 *   tips: string[],            // Short pronunciation tips (FR)
 * }
 *
 * MINIMAL_PAIRS = MinimalPair[]
 * MinimalPair = {
 *   id: string,
 *   phonemeA: string,  // IPA
 *   phonemeB: string,  // IPA
 *   pairs: [string, string][],  // e.g. [['ship', 'sheep'], ['bit', 'beat']]
 *   tipFr: string,
 * }
 *
 * PHONEME_TIPS[ipaSymbol] = {
 *   label: string,      // human-readable name
 *   tipFr: string,      // French tip for producing this sound
 *   example: string,    // English example word
 *   commonError: string // Typical French speaker error
 * }
 */

// ---------------------------------------------------------------------------
// Seed data — a small set of items to make the app functional from day 1.
// The full 10-level corpus will be populated per the Part 2/3 spec.
// ---------------------------------------------------------------------------

export const CORPUS = {
  1: {
    name: 'Les bases',
    nameEn: 'The Basics',
    description: 'Mots du quotidien, sons fondamentaux',
    focus: ['θ', 'ð', 'æ', 'ʌ'],
    items: [
      {
        id: 'l1-001',
        type: 'word',
        text: 'the',
        ipa: '/ðə/',
        translation: 'le, la, les',
        difficulty: 1,
        focusPhonemes: ['ð'],
        tips: ['La langue touche les dents du haut', 'Son soufflé, pas explosif'],
      },
      {
        id: 'l1-002',
        type: 'word',
        text: 'think',
        ipa: '/θɪŋk/',
        translation: 'penser',
        difficulty: 2,
        focusPhonemes: ['θ'],
        tips: ['Langue entre les dents', 'Son soufflé non voisé'],
      },
      {
        id: 'l1-003',
        type: 'word',
        text: 'cat',
        ipa: '/kæt/',
        translation: 'chat',
        difficulty: 1,
        focusPhonemes: ['æ'],
        tips: ['Plus ouvert que le "a" français', 'Bouche très ouverte'],
      },
      {
        id: 'l1-004',
        type: 'word',
        text: 'cup',
        ipa: '/kʌp/',
        translation: 'tasse',
        difficulty: 2,
        focusPhonemes: ['ʌ'],
        tips: ['Voyelle centrale courte', 'Ni "a" ni "o", entre les deux'],
      },
      {
        id: 'l1-005',
        type: 'phrase',
        text: 'Hello, how are you?',
        ipa: '/həˈloʊ haʊ ɑːr juː/',
        translation: 'Bonjour, comment allez-vous ?',
        difficulty: 1,
        focusPhonemes: ['h', 'oʊ', 'juː'],
        tips: ['Le H est aspiré en anglais', 'Diphthongue OW dans "how"'],
      },
      {
        id: 'l1-006',
        type: 'phrase',
        text: 'Thank you very much.',
        ipa: '/θæŋk juː ˈvɛri mʌtʃ/',
        translation: 'Merci beaucoup.',
        difficulty: 2,
        focusPhonemes: ['θ', 'æ', 'ʌ'],
        tips: ['Commencez par θ dans "thank"', 'Distinguez /æ/ dans "thank" et /ʌ/ dans "much"'],
      },
    ],
  },

  2: {
    name: 'Sons vocaliques',
    nameEn: 'Vowel Sounds',
    description: 'Les voyelles anglaises difficiles pour les francophones',
    focus: ['iː', 'ɪ', 'uː', 'ʊ', 'ɛ', 'æ'],
    items: [
      {
        id: 'l2-001',
        type: 'word',
        text: 'ship',
        ipa: '/ʃɪp/',
        translation: 'bateau',
        difficulty: 2,
        focusPhonemes: ['ɪ'],
        tips: ['Court et relâché', 'Pas le même que "sheep"'],
      },
      {
        id: 'l2-002',
        type: 'word',
        text: 'sheep',
        ipa: '/ʃiːp/',
        translation: 'mouton',
        difficulty: 2,
        focusPhonemes: ['iː'],
        tips: ['Long et tendu', 'Lèvres étirées'],
      },
      {
        id: 'l2-003',
        type: 'word',
        text: 'pull',
        ipa: '/pʊl/',
        translation: 'tirer',
        difficulty: 3,
        focusPhonemes: ['ʊ'],
        tips: ['Court et relâché', 'Pas le même que "pool"'],
      },
      {
        id: 'l2-004',
        type: 'word',
        text: 'pool',
        ipa: '/puːl/',
        translation: 'piscine',
        difficulty: 3,
        focusPhonemes: ['uː'],
        tips: ['Long et arrondi', 'Lèvres très arrondies'],
      },
      {
        id: 'l2-005',
        type: 'sentence',
        text: 'The big ship is in the deep sea.',
        ipa: '/ðə bɪɡ ʃɪp ɪz ɪn ðə diːp siː/',
        translation: 'Le grand bateau est dans la mer profonde.',
        difficulty: 3,
        focusPhonemes: ['ɪ', 'iː'],
        tips: ['Distinguez bien ship/deep', 'big=court, deep=long'],
      },
    ],
  },

  3: {
    name: 'Consonnes délicates',
    nameEn: 'Tricky Consonants',
    description: 'TH, V/W, R anglais',
    focus: ['θ', 'ð', 'v', 'w', 'ɹ'],
    items: [
      {
        id: 'l3-001',
        type: 'word',
        text: 'very',
        ipa: '/ˈvɛri/',
        translation: 'très',
        difficulty: 2,
        focusPhonemes: ['v'],
        tips: ['Lèvre inférieure sur les dents du haut', 'V voisé, pas W'],
      },
      {
        id: 'l3-002',
        type: 'word',
        text: 'wine',
        ipa: '/waɪn/',
        translation: 'vin',
        difficulty: 2,
        focusPhonemes: ['w'],
        tips: ['Lèvres arrondies puis ouvertes', 'W n\'est pas V'],
      },
      {
        id: 'l3-003',
        type: 'word',
        text: 'right',
        ipa: '/ɹaɪt/',
        translation: 'droite / correct',
        difficulty: 3,
        focusPhonemes: ['ɹ'],
        tips: ['R rétroflexe, langue vers le haut', 'Jamais roulé comme en français'],
      },
    ],
  },

  4: {
    name: 'Phrases du quotidien',
    nameEn: 'Everyday Phrases',
    description: 'Expressions courantes de la vie quotidienne',
    focus: ['θ', 'ð', 'æ', 'ʌ', 'ɪ', 'v', 'w', 'ɹ'],
    items: [
      {
        id: 'l4-001',
        type: 'phrase',
        text: 'Excuse me, where is the nearest station?',
        ipa: '/ɪkˈskjuːz miː wɛr ɪz ðə ˈnɪərɪst ˈsteɪʃən/',
        translation: 'Excusez-moi, où est la station la plus proche ?',
        difficulty: 3,
        focusPhonemes: ['ð', 'ɹ', 'ɪ', 'w'],
        tips: ['W dans "where" : lèvres arrondies, pas de V', '/ð/ dans "the" — langue entre les dents, voix activée'],
      },
      {
        id: 'l4-002',
        type: 'phrase',
        text: 'Could you repeat that, please?',
        ipa: '/kʊd juː rɪˈpiːt ðæt pliːz/',
        translation: 'Pourriez-vous répéter cela, s\'il vous plaît ?',
        difficulty: 3,
        focusPhonemes: ['ð', 'ɹ', 'iː'],
        tips: ['/ð/ dans "that" — TH voisé, pas un D', 'R rétroflexe dans "repeat" — jamais roulé'],
      },
      {
        id: 'l4-003',
        type: 'phrase',
        text: 'I would like a cup of coffee, please.',
        ipa: '/aɪ wʊd laɪk ə kʌp əv ˈkɒfi pliːz/',
        translation: 'Je voudrais une tasse de café, s\'il vous plaît.',
        difficulty: 3,
        focusPhonemes: ['ʌ', 'v', 'w'],
        tips: ['/ʌ/ dans "cup" — voyelle centrale courte, ni A ni O', '/v/ dans "of" — lèvre inférieure sur les dents du haut'],
      },
      {
        id: 'l4-004',
        type: 'phrase',
        text: 'What time does the next train leave?',
        ipa: '/wɒt taɪm dʌz ðə nɛkst tɹeɪn liːv/',
        translation: 'À quelle heure part le prochain train ?',
        difficulty: 3,
        focusPhonemes: ['ð', 'w', 'ɹ'],
        tips: ['W dans "what" : lèvres arrondies puis qui s\'ouvrent', '/ð/ dans "the" — ne dites pas "de"'],
      },
      {
        id: 'l4-005',
        type: 'phrase',
        text: 'How much does this cost?',
        ipa: '/haʊ mʌtʃ dʌz ðɪs kɒst/',
        translation: 'Combien ça coûte ?',
        difficulty: 3,
        focusPhonemes: ['h', 'ʌ', 'ð'],
        tips: ['H aspiré dans "how" — ne l\'avalez pas comme en français', '/ʌ/ dans "much" — bouche mi-ouverte, langue au centre'],
      },
      {
        id: 'l4-006',
        type: 'sentence',
        text: 'I think this is a very good idea.',
        ipa: '/aɪ θɪŋk ðɪs ɪz ə ˈvɛri ɡʊd aɪˈdɪə/',
        translation: 'Je pense que c\'est une très bonne idée.',
        difficulty: 4,
        focusPhonemes: ['θ', 'ð', 'v', 'ɪ'],
        tips: ['θ dans "think" — TH sourd, langue entre les dents', '/ð/ dans "this" — même position mais avec voix', '/v/ dans "very" — pas un W'],
      },
      {
        id: 'l4-007',
        type: 'phrase',
        text: 'Would you like to come with us?',
        ipa: '/wʊd juː laɪk tə kʌm wɪð ʌs/',
        translation: 'Voudriez-vous venir avec nous ?',
        difficulty: 4,
        focusPhonemes: ['w', 'ð', 'ʌ'],
        tips: ['/w/ dans "would" et "with" — lèvres arrondies', '/ð/ dans "with" — TH voisé en fin de mot'],
      },
      {
        id: 'l4-008',
        type: 'sentence',
        text: 'The weather in England is rather unpredictable.',
        ipa: '/ðə ˈwɛðər ɪn ˈɪŋɡlənd ɪz ˈɹæðər ʌnprɪˈdɪktəbəl/',
        translation: 'La météo en Angleterre est plutôt imprévisible.',
        difficulty: 5,
        focusPhonemes: ['ð', 'w', 'ɹ', 'ʌ', 'ɪ'],
        tips: ['"weather" et "rather" contiennent /ðər/ — TH voisé + R rétroflexe', '/ʌ/ dans "unpredictable" — premier son de la phrase'],
      },
    ],
  },
  5: {
    name: 'Accentuation',
    nameEn: 'Word Stress',
    description: 'Placement de l\'accent tonique en anglais',
    focus: ['ˈ', 'ˌ', 'ə'],
    items: [
      {
        id: 'l5-001',
        type: 'word',
        text: 'photograph',
        ipa: '/ˈfoʊtəɡræf/',
        translation: 'photographie',
        difficulty: 3,
        focusPhonemes: ['ˈ', 'ə'],
        tips: ['Accent sur la 1re syllabe : PHO-to-graph', 'La 2e syllabe est réduite en /tə/'],
      },
      {
        id: 'l5-002',
        type: 'word',
        text: 'photographer',
        ipa: '/fəˈtɒɡrəfər/',
        translation: 'photographe',
        difficulty: 4,
        focusPhonemes: ['ˈ', 'ə'],
        tips: ['Accent sur la 2e syllabe : pho-TOG-ra-pher', 'Comparez avec "photograph" — l\'accent se déplace !'],
      },
      {
        id: 'l5-003',
        type: 'word',
        text: 'comfortable',
        ipa: '/ˈkʌmftəbəl/',
        translation: 'confortable',
        difficulty: 4,
        focusPhonemes: ['ˈ', 'ə', 'ʌ'],
        tips: ['COM-fta-ble — seulement 3 syllabes en anglais courant', 'La 2e syllabe disparaît presque complètement'],
      },
      {
        id: 'l5-004',
        type: 'word',
        text: 'important',
        ipa: '/ɪmˈpɔːrtənt/',
        translation: 'important',
        difficulty: 3,
        focusPhonemes: ['ˈ', 'ə'],
        tips: ['Accent sur la 2e syllabe : im-POR-tant', 'Le français met l\'accent à la fin, l\'anglais non !'],
      },
      {
        id: 'l5-005',
        type: 'phrase',
        text: 'I need to present the present.',
        ipa: '/aɪ niːd tə prɪˈzɛnt ðə ˈprɛzənt/',
        translation: 'Je dois présenter le cadeau.',
        difficulty: 5,
        focusPhonemes: ['ˈ', 'ɪ'],
        tips: ['"present" (verbe) : pré-SENT, accent à la fin', '"present" (nom) : PRÉ-sent, accent au début', 'Même orthographe, sens différent selon l\'accentuation'],
      },
      {
        id: 'l5-006',
        type: 'sentence',
        text: 'The economy is recovering gradually.',
        ipa: '/ðə ɪˈkɒnəmi ɪz rɪˈkʌvərɪŋ ˈɡrædjuəli/',
        translation: 'L\'économie se rétablit progressivement.',
        difficulty: 5,
        focusPhonemes: ['ˈ', 'ə', 'ɪ'],
        tips: ['e-CO-no-my : accent sur la 2e syllabe', 're-CO-ve-ring : accent sur la 2e syllabe', 'GRA-dua-lly : accent sur la 1re syllabe'],
      },
      {
        id: 'l5-007',
        type: 'sentence',
        text: 'She is incredibly enthusiastic about photography.',
        ipa: '/ʃiː ɪz ɪnˈkrɛdɪbli ɪnˌθjuːziˈæstɪk əˈbaʊt fəˈtɒɡrəfi/',
        translation: 'Elle est incroyablement enthousiaste à propos de la photographie.',
        difficulty: 6,
        focusPhonemes: ['ˈ', 'ˌ', 'ə'],
        tips: ['in-CRE-di-bly : accent sur la 2e syllabe', 'en-thu-si-AS-tic : accent sur la 4e syllabe', 'pho-TOG-ra-phy : accent sur la 2e syllabe'],
      },
    ],
  },

  6: {
    name: 'Intonation',
    nameEn: 'Intonation',
    description: 'Courbes mélodiques et questions en anglais',
    focus: ['↗', '↘', 'tag questions'],
    items: [
      {
        id: 'l6-001',
        type: 'phrase',
        text: 'Are you coming tomorrow?',
        ipa: '/ɑːr juː ˈkʌmɪŋ təˈmɒroʊ↗/',
        translation: 'Tu viens demain ?',
        difficulty: 3,
        focusPhonemes: ['ɹ', 'ʌ', 'ɒ'],
        tips: ['Question oui/non → voix qui monte à la fin', 'Montez sur "tomorrow" pour marquer la question', 'Différent du français où toute la phrase monte'],
      },
      {
        id: 'l6-002',
        type: 'phrase',
        text: 'Where are you going?',
        ipa: '/wɛr ɑːr juː ˈɡoʊɪŋ↘/',
        translation: 'Où vas-tu ?',
        difficulty: 3,
        focusPhonemes: ['w', 'ɹ', 'oʊ'],
        tips: ['Question WH (who, what, where, when, why, how) → voix qui descend à la fin', 'Différent des questions oui/non', 'Montez légèrement au milieu, puis descendez'],
      },
      {
        id: 'l6-003',
        type: 'phrase',
        text: 'It\'s cold today, isn\'t it?',
        ipa: '/ɪts koʊld təˈdeɪ ˈɪznt ɪt↗/',
        translation: 'Il fait froid aujourd\'hui, n\'est-ce pas ?',
        difficulty: 4,
        focusPhonemes: ['oʊ', 'ɪ'],
        tips: ['Tag question : petite question ajoutée à la fin', 'Si vous êtes incertain → montez sur "isn\'t it"', 'Si vous cherchez confirmation → descendez sur "isn\'t it"'],
      },
      {
        id: 'l6-004',
        type: 'phrase',
        text: 'I\'d like coffee, tea, or juice.',
        ipa: '/aɪd laɪk ˈkɒfi↗ tiː↗ ɔːr dʒuːs↘/',
        translation: 'Je voudrais du café, du thé ou du jus.',
        difficulty: 4,
        focusPhonemes: ['ɒ', 'iː', 'dʒ'],
        tips: ['Liste : montez sur chaque élément sauf le dernier', 'Dernier élément → descendez pour indiquer la fin', 'café↗ thé↗ jus↘'],
      },
      {
        id: 'l6-005',
        type: 'sentence',
        text: 'When you arrive, call me.',
        ipa: '/wɛn juː əˈraɪv↗ kɔːl miː↘/',
        translation: 'Quand tu arrives, appelle-moi.',
        difficulty: 4,
        focusPhonemes: ['w', 'ɹ', 'ɔː'],
        tips: ['Proposition conditionnelle : montez à la fin de la subordonnée', 'Descendez à la fin de la phrase principale', 'Cette pause mélodique sépare les deux parties'],
      },
      {
        id: 'l6-006',
        type: 'sentence',
        text: 'He said he would come, didn\'t he?',
        ipa: '/hiː sɛd hiː wʊd kʌm ˈdɪdnt hiː↗/',
        translation: 'Il a dit qu\'il viendrait, n\'est-ce pas ?',
        difficulty: 5,
        focusPhonemes: ['ɛ', 'ʊ', 'ʌ'],
        tips: ['Tag question négative → voix monte si on attend une confirmation', 'Descendre exprime plus de certitude', 'Contraste clair entre la phrase principale (descendante) et le tag (montant)'],
      },
      {
        id: 'l6-007',
        type: 'sentence',
        text: 'Could you tell me how to get to the museum?',
        ipa: '/kʊd juː tɛl miː haʊ tə ɡɛt tə ðə mjuːˈziːəm↘/',
        translation: 'Pourriez-vous me dire comment aller au musée ?',
        difficulty: 5,
        focusPhonemes: ['ʊ', 'h', 'iː'],
        tips: ['Question polie avec WH (how) → descend à la fin', 'Même si la forme est une question oui/non, la WH interne guide l\'intonation', 'Ton montant sur "museum" sonnerait bizarre'],
      },
    ],
  },

  7: {
    name: 'Mots liés',
    nameEn: 'Connected Speech',
    description: 'Liaison, assimilation et élision dans le discours naturel',
    focus: ['liaison', 'élision', 'assimilation'],
    items: [
      {
        id: 'l7-001',
        type: 'phrase',
        text: 'pick it up',
        ipa: '/ˈpɪk ɪt ʌp/ → /ˈpɪkɪdʌp/',
        translation: 'ramasser ça',
        difficulty: 3,
        focusPhonemes: ['ɪ', 'ʌ'],
        tips: ['En discours naturel : les mots se lient', '"pick it up" → sons enchaînés "PICKidUP"', 'Le /t/ entre voyelles devient souvent /d/ (flap américain)'],
      },
      {
        id: 'l7-002',
        type: 'phrase',
        text: 'turn it on',
        ipa: '/tɜːrn ɪt ɒn/ → /ˈtɜːrnɪdɒn/',
        translation: 'l\'allumer',
        difficulty: 3,
        focusPhonemes: ['ɜː', 'ɪ', 'ɒ'],
        tips: ['Les voyelles initiales s\'accrochent à la consonne précédente', '"turn it on" → "TURNidON"', 'Continuité : ne faites pas de pauses entre les mots'],
      },
      {
        id: 'l7-003',
        type: 'phrase',
        text: 'Did you eat yet?',
        ipa: '/dɪd juː iːt jɛt/ → /ˈdɪdʒuː ˈiːtjɛt/',
        translation: 'Tu as déjà mangé ?',
        difficulty: 4,
        focusPhonemes: ['dʒ', 'iː', 'j'],
        tips: ['"Did you" → /dɪdʒuː/ : le D et Y fusionnent en /dʒ/ (comme dans "judge")', 'Assimilation : deux sons adjacents se combinent', 'Très courant en anglais américain et britannique'],
      },
      {
        id: 'l7-004',
        type: 'phrase',
        text: 'I\'m going to see you next week.',
        ipa: '/aɪm ˈɡoʊɪŋ tə siː juː ˈnɛkst wiːk/',
        translation: 'Je vais te voir la semaine prochaine.',
        difficulty: 4,
        focusPhonemes: ['oʊ', 'ə', 'iː'],
        tips: ['"going to" → /ˈɡoʊɪŋ tə/ — "to" est réduit à /tə/', 'En discours très rapide : "gonna" /ˈɡɒnə/', '"see you" → /siːjuː/ — liaison entre voyelle et consonne Y'],
      },
      {
        id: 'l7-005',
        type: 'sentence',
        text: 'What are you up to?',
        ipa: '/wɒt ɑːr juː ʌp tuː/ → /ˈwɒdərjuː ˈʌptə/',
        translation: 'Qu\'est-ce que tu fais ?',
        difficulty: 4,
        focusPhonemes: ['ɒ', 'ɑː', 'ə'],
        tips: ['"What are" → /wɒdər/ : le T devient un D (flap), "are" perd son /r/ initial', '"you up" → /juːʌp/ : liaison directe entre les deux mots', 'La phrase entière s\'enchaîne sans pauses'],
      },
      {
        id: 'l7-006',
        type: 'sentence',
        text: 'Could you pass me the salt and pepper?',
        ipa: '/kʊd juː pɑːs miː ðə sɔːlt ən ˈpɛpər/',
        translation: 'Pourriez-vous me passer le sel et le poivre ?',
        difficulty: 4,
        focusPhonemes: ['ʊ', 'dʒ', 'ə', 'ɔː'],
        tips: ['"Could you" → /kʊdʒuː/ : D+Y → /dʒ/', '"and" → /ən/ ou même /n/ : réduit en discours naturel', '"salt and pepper" → "SALT\'n\'PEPPER" : enchaînement rapide'],
      },
      {
        id: 'l7-007',
        type: 'sentence',
        text: 'Let me know if there is anything I can do for you.',
        ipa: '/lɛt miː noʊ ɪf ðɛr ɪz ˈɛniθɪŋ aɪ kən duː fər juː/',
        translation: 'Dites-moi s\'il y a quoi que ce soit que je puisse faire pour vous.',
        difficulty: 6,
        focusPhonemes: ['ɛ', 'oʊ', 'ə', 'ð'],
        tips: ['"Let me" → /lɛtmiː/ : pas de pause entre les deux mots', '"if there is" → /ɪfðɛrɪz/ : tout s\'enchaîne', '"can" → /kən/ : réduit en discours normal (forme faible)'],
      },
    ],
  },

  8: {
    name: 'Réductions',
    nameEn: 'Reductions & Contractions',
    description: 'Formes réduites et contractions du discours courant',
    focus: ['gonna', 'wanna', 'kinda', 'weak forms'],
    items: [
      {
        id: 'l8-001',
        type: 'phrase',
        text: 'I\'m gonna call you later.',
        ipa: '/aɪm ˈɡɒnə kɔːl juː ˈleɪtər/',
        translation: 'Je vais t\'appeler plus tard.',
        difficulty: 3,
        focusPhonemes: ['ɒ', 'ə', 'ɔː'],
        tips: ['"gonna" = "going to" en discours informel', 'Prononcez /ˈɡɒnə/ — deux syllabes seulement', 'Courant dans la conversation mais pas à l\'écrit formel'],
      },
      {
        id: 'l8-002',
        type: 'phrase',
        text: 'Do you wanna come with us?',
        ipa: '/duː juː ˈwɒnə kʌm wɪð ʌs/',
        translation: 'Tu veux venir avec nous ?',
        difficulty: 3,
        focusPhonemes: ['ɒ', 'ə', 'ʌ'],
        tips: ['"wanna" = "want to" en discours informel', 'Prononcez /ˈwɒnə/ — deux syllabes', 'Ne pas confondre avec "wanna" (want a) vs "wanna" (want to)'],
      },
      {
        id: 'l8-003',
        type: 'phrase',
        text: 'I dunno, maybe.',
        ipa: '/aɪ dəˈnoʊ ˈmeɪbi/',
        translation: 'Je sais pas, peut-être.',
        difficulty: 3,
        focusPhonemes: ['ə', 'oʊ', 'eɪ'],
        tips: ['"dunno" = "don\'t know" très réduit', 'Prononcez /dəˈnoʊ/ — accent sur la 2e syllabe', 'Très informel — à éviter en contexte professionnel'],
      },
      {
        id: 'l8-004',
        type: 'phrase',
        text: 'She\'s kinda tired, I think.',
        ipa: '/ʃiːz ˈkaɪndə ˈtaɪərd aɪ θɪŋk/',
        translation: 'Elle est un peu fatiguée, je crois.',
        difficulty: 4,
        focusPhonemes: ['aɪ', 'ə', 'θ'],
        tips: ['"kinda" = "kind of" : modifieur de degré informel', 'Prononcez /ˈkaɪndə/ — accent sur la 1re syllabe', '"sorta" (sort of) et "kinda" sont très fréquents en anglais oral'],
      },
      {
        id: 'l8-005',
        type: 'sentence',
        text: 'I could\'ve told you that was gonna happen.',
        ipa: '/aɪ ˈkʊdəv toʊld juː ðæt wəz ˈɡɒnə ˈhæpən/',
        translation: 'J\'aurais pu te dire que ça allait arriver.',
        difficulty: 5,
        focusPhonemes: ['ʊ', 'ə', 'ɒ', 'æ'],
        tips: ['"could\'ve" = "could have" : /ˈkʊdəv/ — jamais "could of" !',' "gonna happen" : les deux formes réduites s\'enchaînent naturellement', 'En discours rapide : "I coulda told ya"'],
      },
      {
        id: 'l8-006',
        type: 'sentence',
        text: 'He should\'ve been there but he wasn\'t.',
        ipa: '/hiː ˈʃʊdəv bɪn ðɛr bʌt hiː ˈwɒznt/',
        translation: 'Il aurait dû être là mais il n\'était pas.',
        difficulty: 5,
        focusPhonemes: ['ʊ', 'ə', 'ɪ', 'ɒ'],
        tips: ['"should\'ve" = "should have" : /ˈʃʊdəv/', '"wasn\'t" : contraction naturelle en discours', 'Le "have" est toujours réduit en /əv/ après les modaux'],
      },
      {
        id: 'l8-007',
        type: 'sentence',
        text: 'What\'d you do last night? I\'d\'ve gone out but I was too tired.',
        ipa: '/wɒtʃəd juː duː lɑːst naɪt aɪdəv ɡɒn aʊt bʌt aɪ wəz tuː ˈtaɪərd/',
        translation: 'T\'as fait quoi hier soir ? Je serais sorti mais j\'étais trop fatigué.',
        difficulty: 7,
        focusPhonemes: ['ɒ', 'ə', 'aɪ', 'ʌ'],
        tips: ['"What\'d" = "What did" : /wɒtʃəd/ — D+Y fusionnent', '"I\'d\'ve" = "I would have" : triple réduction en /aɪdəv/', 'Ce niveau de réduction est courant dans une conversation détendue'],
      },
    ],
  },

  9: {
    name: 'Registres',
    nameEn: 'Formal vs Informal',
    description: 'Adapter son anglais selon le contexte',
    focus: ['register', 'formality', 'politeness'],
    items: [
      {
        id: 'l9-001',
        type: 'phrase',
        text: 'Could I possibly speak with Mr. Johnson, please?',
        ipa: '/kʊd aɪ ˈpɒsɪbli spiːk wɪð ˈmɪstər ˈdʒɒnsən pliːz/',
        translation: 'Pourrais-je parler à M. Johnson, s\'il vous plaît ?',
        difficulty: 4,
        focusPhonemes: ['ʊ', 'ɒ', 'iː', 'dʒ'],
        tips: ['Registre très formel : "Could I possibly..." sonne poli et professionnel', 'Informel équivalent : "Can I talk to Johnson?"', 'La prosodie est plus soignée et mesurée en registre formel'],
      },
      {
        id: 'l9-002',
        type: 'phrase',
        text: 'Hey, is Johnson around?',
        ipa: '/heɪ ɪz ˈdʒɒnsən əˈraʊnd/',
        translation: 'Hé, Johnson est là ?',
        difficulty: 3,
        focusPhonemes: ['eɪ', 'dʒ', 'ə'],
        tips: ['Registre très informel : "Hey" + prénom seul', 'Prononciation plus rapide et détendue', 'Convient entre collègues proches — pas avec un supérieur'],
      },
      {
        id: 'l9-003',
        type: 'sentence',
        text: 'I am writing to enquire about the position advertised on your website.',
        ipa: '/aɪ æm ˈraɪtɪŋ tə ɪnˈkwaɪər əˈbaʊt ðə pəˈzɪʃən ˈædvətaɪzd ɒn jɔːr ˈwɛbsaɪt/',
        translation: 'Je vous écris pour me renseigner sur le poste annoncé sur votre site.',
        difficulty: 5,
        focusPhonemes: ['ɪ', 'ə', 'ɒ', 'eɪ'],
        tips: ['Registre formel écrit/oral : tous les mots prononcés clairement', '"I am" au lieu de "I\'m" — les contractions sont souvent évitées', 'Chaque syllabe a du poids, le débit est mesuré'],
      },
      {
        id: 'l9-004',
        type: 'sentence',
        text: 'Saw the job ad online. Sounds interesting, thought I\'d apply.',
        ipa: '/sɔː ðə dʒɒb æd ˈɒnlaɪn saʊndz ɪnˈtrɛstɪŋ θɔːt aɪd əˈplaɪ/',
        translation: 'J\'ai vu l\'annonce en ligne. Ça a l\'air intéressant, j\'ai pensé postuler.',
        difficulty: 5,
        focusPhonemes: ['ɔː', 'dʒ', 'aʊ', 'ɪ'],
        tips: ['Registre très informel : sujets omis ("Saw" au lieu de "I saw")', 'Débit rapide avec réductions naturelles', 'Convient à une conversation entre amis, pas à un entretien'],
      },
      {
        id: 'l9-005',
        type: 'sentence',
        text: 'I would appreciate it if you could confirm your attendance by Friday.',
        ipa: '/aɪ wʊd əˈpriːʃieɪt ɪt ɪf juː kʊd kənˈfɜːrm jɔːr əˈtɛndəns baɪ ˈfraɪdeɪ/',
        translation: 'Je vous serais reconnaissant de bien vouloir confirmer votre présence avant vendredi.',
        difficulty: 6,
        focusPhonemes: ['iː', 'ɜː', 'ə', 'eɪ'],
        tips: ['"I would appreciate it if..." : structure formelle et indirecte', 'Articulez "appreciate" clairement : a-PRE-ci-ate', 'Évitez les réductions : dites "I would", pas "I\'d"'],
      },
      {
        id: 'l9-006',
        type: 'sentence',
        text: 'No worries, just let me know what works for you and we\'ll sort it out.',
        ipa: '/noʊ ˈwʌriz dʒʌst lɛt miː noʊ wɒt wɜːrks fər juː ən wiːl sɔːrt ɪt aʊt/',
        translation: 'Pas de souci, dis-moi juste ce qui t\'arrange et on trouvera une solution.',
        difficulty: 5,
        focusPhonemes: ['oʊ', 'ʌ', 'ɒ', 'ɜː'],
        tips: ['"No worries" : expression informelle très courante', '"sort it out" : phrasal verb informel', 'Débit naturel avec formes réduites : "we\'ll", "let me"'],
      },
      {
        id: 'l9-007',
        type: 'sentence',
        text: 'On behalf of the entire team, I would like to extend our sincere congratulations.',
        ipa: '/ɒn bɪˈhɑːf əv ðə ɪnˈtaɪər tiːm aɪ wʊd laɪk tə ɪkˈstɛnd aʊər sɪnˈsɪər kənˌɡræʧʊˈleɪʃənz/',
        translation: 'Au nom de toute l\'équipe, je souhaite vous adresser nos sincères félicitations.',
        difficulty: 7,
        focusPhonemes: ['ɑː', 'aɪ', 'ɪ', 'eɪ'],
        tips: ['"On behalf of" : expression formelle clé — prononcez /bɪˈhɑːf/', '"sincere congratulations" : articulez chaque syllabe', 'Le registre cérémoniaire demande un débit lent et maîtrisé'],
      },
    ],
  },

  10: {
    name: 'Maîtrise',
    nameEn: 'Mastery',
    description: 'Défi final — tous les sons et schémas combinés',
    focus: ['θ', 'ð', 'ɹ', 'v', 'w', 'æ', 'ʌ', 'iː', 'ɪ', 'ˈ', 'liaison'],
    items: [
      {
        id: 'l10-001',
        type: 'sentence',
        text: 'Whether the weather is good or not, we\'re going to the theatre.',
        ipa: '/ˈwɛðər ðə ˈwɛðər ɪz ɡʊd ɔːr nɒt wɪər ˈɡoʊɪŋ tə ðə ˈθɪətər/',
        translation: 'Que le temps soit beau ou non, nous allons au théâtre.',
        difficulty: 6,
        focusPhonemes: ['ð', 'w', 'ɹ', 'θ', 'ɪ'],
        tips: ['"Whether" et "weather" sont des homophones : /ˈwɛðər/', '"theatre" : TH sourd /θ/ + R rétroflexe', '"we\'re" = /wɪər/ : liaison W+voyelle'],
      },
      {
        id: 'l10-002',
        type: 'sentence',
        text: 'The thirty-three thieves thought that they thrived through the Thursday thunderstorm.',
        ipa: '/ðə ˌθɜːrtiˈθriː θiːvz θɔːt ðæt ðeɪ θraɪvd θruː ðə ˈθɜːrzdeɪ ˈθʌndərstɔːrm/',
        translation: 'Les trente-trois voleurs pensaient qu\'ils prospéraient pendant la tempête de jeudi.',
        difficulty: 8,
        focusPhonemes: ['θ', 'ð'],
        tips: ['Défi TH total : alternez /θ/ (sourd) et /ð/ (voisé)', '"thirty" et "Thursday" : /θ/ sourd', '"the", "that", "they", "through" : /ð/ voisé'],
      },
      {
        id: 'l10-003',
        type: 'sentence',
        text: 'Rural breweries rarely brew regular red ales in February.',
        ipa: '/ˈrʊərəl ˈbruːəriz ˈrɛrli bruː ˈrɛɡjʊlər rɛd eɪlz ɪn ˈfɛbruəri/',
        translation: 'Les brasseries rurales font rarement des ales rouges ordinaires en février.',
        difficulty: 8,
        focusPhonemes: ['ɹ', 'ʊ', 'ə'],
        tips: ['Défi R : chaque mot contient le R rétroflexe anglais', 'Jamais roulé, jamais tu', '"rural" : deux R à ne pas confondre avec un son guttural'],
      },
      {
        id: 'l10-004',
        type: 'sentence',
        text: 'I would have thought that she could have done it better if she\'d wanted to.',
        ipa: '/aɪ wʊdəv θɔːt ðæt ʃiː kʊdəv dʌn ɪt ˈbɛtər ɪf ʃiːd ˈwɒntɪd tuː/',
        translation: 'J\'aurais cru qu\'elle aurait pu le faire mieux si elle l\'avait voulu.',
        difficulty: 7,
        focusPhonemes: ['ʊ', 'ə', 'ɒ', 'θ'],
        tips: ['"would have" → /wʊdəv/ : réduction naturelle', '"could have" → /kʊdəv/ : même pattern', '"better" : T entre voyelles → /d/ en américain (flap)'],
      },
      {
        id: 'l10-005',
        type: 'sentence',
        text: 'She ships cheap sheep sheets, while he ships deep sea shells.',
        ipa: '/ʃiː ʃɪps tʃiːp ʃiːp ʃiːts waɪl hiː ʃɪps diːp siː ʃɛlz/',
        translation: 'Elle expédie des draps en laine bon marché, pendant qu\'il expédie des coquillages de mer profonde.',
        difficulty: 7,
        focusPhonemes: ['ʃ', 'iː', 'ɪ', 'tʃ'],
        tips: ['Distinguez /ɪ/ (ships, ship, while) et /iː/ (cheap, sheets, sheep, deep, sea)', 'Le SH /ʃ/ est constant — lèvres arrondies, langue en arrière', '"cheap" commence par /tʃ/ — différent de SH'],
      },
      {
        id: 'l10-006',
        type: 'sentence',
        text: 'The ambitious entrepreneur enthusiastically presented the extraordinary innovation to an international audience.',
        ipa: '/ðə æmˈbɪʃəs ˌɒntrəprəˈnɜːr ɪnˌθjuːziˈæstɪkli prɪˈzɛntɪd ðɪ ɪkˈstrɔːrdɪnɛri ˌɪnəˈveɪʃən tuː ən ˌɪntərˈnæʃənl ˈɔːdiəns/',
        translation: 'L\'entrepreneur ambitieux a présenté avec enthousiasme l\'innovation extraordinaire à un public international.',
        difficulty: 9,
        focusPhonemes: ['æ', 'ɪ', 'ə', 'eɪ', 'ɜː'],
        tips: ['"entrepreneur" : /ˌɒntrəprəˈnɜːr/ — accent sur la dernière syllabe', '"enthusiastically" : en-thu-si-AS-tic-ally — 7 syllabes !', '"extraordinary" : ex-TRAOR-di-na-ry — accent sur la 2e syllabe'],
      },
      {
        id: 'l10-007',
        type: 'sentence',
        text: 'When did you get a chance to think through everything we discussed regarding the rather complicated situation?',
        ipa: '/wɛn dɪd juː ɡɛt ə tʃɑːns tə θɪŋk θruː ˈɛvriθɪŋ wiː dɪˈskʌst rɪˈɡɑːrdɪŋ ðə ˈrɑːðər ˈkɒmplɪkeɪtɪd ˌsɪtʃuˈeɪʃən/',
        translation: 'Quand as-tu eu l\'occasion de réfléchir à tout ce dont nous avons discuté concernant la situation assez complexe ?',
        difficulty: 8,
        focusPhonemes: ['θ', 'ð', 'ɹ', 'ɪ', 'ə'],
        tips: ['"think through everything" : trois mots avec TH — θ, θ, θ !', '"rather complicated situation" : /ð/, puis /ɹ/ × 2, puis /ʃ/', '"discussed regarding" : D+Y → /dʒ/ potentiel, puis /ɹ/ rétroflexe'],
      },
      {
        id: 'l10-008',
        type: 'sentence',
        text: 'Variety is the very spice of life; without variety, we\'d wither away.',
        ipa: '/vəˈraɪəti ɪz ðə ˈvɛri spaɪs əv laɪf wɪˈðaʊt vəˈraɪəti wiːd ˈwɪðər əˈweɪ/',
        translation: 'La variété est le piment de la vie ; sans variété, nous nous étiolerions.',
        difficulty: 8,
        focusPhonemes: ['v', 'w', 'ð', 'ɹ', 'aɪ'],
        tips: ['"Variety" et "very" : V bien frotté, lèvre inférieure sur les dents', '"without" et "wither" : W arrondi puis /ð/ voisé', 'Contrastez V (/v/) et W (/w/) — sons très différents en anglais'],
      },
    ],
  },
};

// ---------------------------------------------------------------------------
// Minimal pairs — for discriminating between commonly confused sounds
// ---------------------------------------------------------------------------

export const MINIMAL_PAIRS = [
  {
    id: 'mp-001',
    phonemeA: 'ɪ',
    phonemeB: 'iː',
    pairs: [
      ['ship', 'sheep'],
      ['bit', 'beat'],
      ['sit', 'seat'],
      ['live', 'leave'],
      ['fill', 'feel'],
    ],
    tipFr: 'Le son /ɪ/ est court et relâché, /iː/ est long et tendu avec les lèvres étirées.',
  },
  {
    id: 'mp-002',
    phonemeA: 'ʊ',
    phonemeB: 'uː',
    pairs: [
      ['pull', 'pool'],
      ['full', 'fool'],
      ['look', 'Luke'],
      ['good', 'food'],
    ],
    tipFr: '/ʊ/ est court et détendu, /uː/ est long avec les lèvres très arrondies.',
  },
  {
    id: 'mp-003',
    phonemeA: 'θ',
    phonemeB: 's',
    pairs: [
      ['think', 'sink'],
      ['three', 'sea'],
      ['thank', 'sank'],
      ['thin', 'sin'],
      ['mouth', 'mouse'],
    ],
    tipFr: '/θ/ se prononce langue entre les dents, /s/ avec la langue en arrière des dents du haut.',
  },
  {
    id: 'mp-004',
    phonemeA: 'ð',
    phonemeB: 'z',
    pairs: [
      ['this', 'zis'],
      ['there', 'zare'],
      ['though', 'zo'],
    ],
    tipFr: '/ð/ est le TH sonore (la, the, this) — langue entre les dents avec voix.',
  },
  {
    id: 'mp-005',
    phonemeA: 'v',
    phonemeB: 'w',
    pairs: [
      ['vine', 'wine'],
      ['vet', 'wet'],
      ['veil', 'wail'],
      ['vest', 'west'],
    ],
    tipFr: '/v/ : lèvre inférieure sur les dents du haut. /w/ : lèvres arrondies qui s\'ouvrent.',
  },
  {
    id: 'mp-006',
    phonemeA: 'æ',
    phonemeB: 'ɛ',
    pairs: [
      ['bad', 'bed'],
      ['sad', 'said'],
      ['hat', 'het'],
      ['man', 'men'],
      ['bag', 'beg'],
    ],
    tipFr: '/æ/ est plus ouvert que /ɛ/ — bouche plus grande, mâchoire plus basse.',
  },
];

// ---------------------------------------------------------------------------
// Phoneme tips — reference guide for individual IPA sounds
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Multiplayer phrases — sentences of increasing difficulty for French speakers
// Each "tier" is progressively harder (phonemes, length, connected speech)
// ---------------------------------------------------------------------------

export const MULTIPLAYER_PHRASES = [
  // Tier 1 — Short & basic (difficulty 1-2)
  { text: 'This is the thing.',                   difficulty: 1 },
  { text: 'I think it is good.',                  difficulty: 1 },
  { text: 'The cat sat on the hat.',              difficulty: 1 },
  { text: 'Where is the cup?',                    difficulty: 1 },
  { text: 'How are you today?',                   difficulty: 1 },
  { text: 'She has a red bag.',                    difficulty: 1 },
  { text: 'Thank you very much.',                 difficulty: 2 },
  { text: 'Would you like some water?',           difficulty: 2 },
  { text: 'He lives in a big house.',             difficulty: 2 },
  { text: 'What time is it right now?',           difficulty: 2 },

  // Tier 2 — TH + vowel contrasts (difficulty 3-4)
  { text: 'I thought those three things through.',             difficulty: 3 },
  { text: 'The weather was rather warm this Thursday.',        difficulty: 3 },
  { text: 'His brother and his father went there together.',   difficulty: 3 },
  { text: 'She ships cheap sheep sheets every week.',          difficulty: 3 },
  { text: 'He stood by the wooden hook and took a good look.',  difficulty: 4 },
  { text: 'The thin man thinks thick thoughts.',               difficulty: 4 },
  { text: 'Thirty-three thirsty thieves thought thoroughly.', difficulty: 4 },
  { text: 'He breathed through his teeth with ease.',          difficulty: 4 },
  { text: 'Which witch watched which watch?',                  difficulty: 4 },
  { text: 'She grabbed her black backpack and ran back past the camp.', difficulty: 4 },

  // Tier 3 — V/W + R + connected speech (difficulty 5-6)
  { text: 'Very well, the vine and the wine are both fine.',                difficulty: 5 },
  { text: 'The world is a wonderful and weird place to explore.',           difficulty: 5 },
  { text: 'Rural breweries rarely brew regular red ales.',                  difficulty: 5 },
  { text: 'We were wary of the very heavy rain on Wednesday.',             difficulty: 6 },
  { text: 'Her third birthday party was on the first of February.',        difficulty: 6 },
  { text: 'The warrior worried whether the weather would worsen.',         difficulty: 6 },
  { text: 'Roger realized the railway ran through the rural area.',        difficulty: 6 },
  { text: 'Whoever reviews the work will rewrite the worst parts.',        difficulty: 6 },
  { text: 'Variety is the very spice of life, is it not?',                 difficulty: 5 },
  { text: 'Will you walk with us or wait in the van?',                     difficulty: 5 },

  // Tier 4 — Reductions, weak forms, stress (difficulty 7-8)
  { text: 'I could have gone to the store, but I would have been late.',             difficulty: 7 },
  { text: 'She should have told him that she was not going to be there.',             difficulty: 7 },
  { text: 'What do you think you are going to do about it?',                         difficulty: 7 },
  { text: 'He is not the kind of person who would have said something like that.',   difficulty: 7 },
  { text: 'The photograph and the photographer photographed the photography.',       difficulty: 8 },
  { text: 'An anonymous analysis of the analytical data was thoroughly examined.',    difficulty: 8 },
  { text: 'The comfortable temperature was comparable to a Mediterranean climate.',  difficulty: 8 },
  { text: 'Particularly, the parliamentary secretary was characteristically quiet.',  difficulty: 8 },
  { text: 'The entrepreneurs were enthusiastically entrepreneurial.',                difficulty: 8 },
  { text: 'A considerable percentage of the population participated voluntarily.',   difficulty: 8 },

  // Tier 5 — Tongue twisters & mastery (difficulty 9-10)
  { text: 'The sixth sick sheik\'s sixth sheep\'s sick.',                                          difficulty: 9 },
  { text: 'She sells seashells by the seashore and the shells she sells are seashells for sure.', difficulty: 9 },
  { text: 'How much wood would a woodchuck chuck if a woodchuck could chuck wood?',               difficulty: 9 },
  { text: 'Peter Piper picked a peck of pickled peppers.',                                         difficulty: 9 },
  { text: 'Red lorry, yellow lorry, red lorry, yellow lorry.',                                     difficulty: 9 },
  { text: 'Through three cheese trees, three free fleas flew.',                                    difficulty: 10 },
  { text: 'The thirty-three thieves thought that they thrilled the throne throughout Thursday.',   difficulty: 10 },
  { text: 'Whether the weather is warm, whether the weather is hot, we have to put up with the weather whether we like it or not.', difficulty: 10 },
  { text: 'Uniquely, the quinquennial queue for the boutique was quite picturesque.',              difficulty: 10 },
  { text: 'The epitome of hyperbole is not synonymous with catastrophe.',                          difficulty: 10 },
];

// ---------------------------------------------------------------------------
// Fun-mode phrases — tongue twisters, nonsense sentences, and classic traps
// ---------------------------------------------------------------------------

export const MULTIPLAYER_FUN_PHRASES = [
  // Easy fun (difficulty 1-2)
  { text: 'My cat is fat and sat on a flat mat.',                                                   difficulty: 1 },
  { text: 'The big pig did a jig in the fog.',                                                      difficulty: 1 },
  { text: 'Bob ate a corn cob on a log by a bog.',                                                  difficulty: 1 },
  { text: 'A fat bat sat on a flat hat.',                                                           difficulty: 2 },
  { text: 'I wish to wish the wish you wish to wish.',                                              difficulty: 2 },

  // Medium (difficulty 3-4)
  { text: 'Bad lads had glad dads in the sand.',                                                    difficulty: 3 },
  { text: 'Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair.',                                       difficulty: 3 },
  { text: 'There those three thin thieves thought.',                                                difficulty: 3 },
  { text: 'Toy boat, toy boat, toy boat.',                                                          difficulty: 4 },
  { text: 'Lesser leather never weathered wetter weather better.',                                  difficulty: 4 },
  { text: 'Unique New York, unique New York, you know you need unique New York.',                    difficulty: 4 },

  // Hard (difficulty 5-6)
  { text: 'Moses supposes his toeses are roses, but Moses supposes erroneously.',                   difficulty: 5 },
  { text: 'A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.', difficulty: 5 },
  { text: 'Silly Sally swiftly shooed seven silly sheep southward.',                                difficulty: 6 },
  { text: 'I thought a thought, but the thought I thought was not the thought I thought I thought.', difficulty: 6 },

  // Very hard (difficulty 7-8)
  { text: 'How can a clam cram in a clean cream can?',                                              difficulty: 7 },
  { text: 'Send toast to ten tense stout saints\' ten tall tents.',                                 difficulty: 7 },
  { text: 'Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons.',   difficulty: 8 },
  { text: 'The seething sea ceaseth and thus the seething sea sufficeth us.',                       difficulty: 8 },

  // Extreme (difficulty 9-10)
  { text: 'The sixth sick sheik\'s sixth sheep\'s sick.',                                           difficulty: 9 },
  { text: 'She sells seashells by the seashore and the shells she sells are seashells for sure.',   difficulty: 9 },
  { text: 'How much wood would a woodchuck chuck if a woodchuck could chuck wood?',                 difficulty: 9 },
  { text: 'Peter Piper picked a peck of pickled peppers. Did Peter Piper pick a peck of pickled peppers?', difficulty: 10 },
  { text: 'Whether the weather is warm, whether the weather is hot, we have to put up with the weather whether we like it or not.', difficulty: 10 },
  { text: 'Through three cheese trees three free fleas flew. While these fleas flew, freezy breeze blew.', difficulty: 10 },
];

export const PHONEME_TIPS = {
  'θ': {
    label: 'TH sourd (think)',
    tipFr: 'Placez le bout de la langue entre les dents du haut et soufflez doucement. Son non voisé.',
    example: 'think, three, both',
    commonError: 'Remplacé par /s/ ou /t/ par les francophones',
  },
  'ð': {
    label: 'TH sonore (the)',
    tipFr: 'Comme /θ/ mais avec vibration des cordes vocales. Langue entre les dents, voix activée.',
    example: 'the, this, that, there',
    commonError: 'Remplacé par /z/ ou /d/ par les francophones',
  },
  'æ': {
    label: 'A ouvert (cat)',
    tipFr: 'Voyelle très ouverte entre /a/ et /ɛ/. Bouche très ouverte, mâchoire basse.',
    example: 'cat, bad, man, apple',
    commonError: 'Prononcé comme /a/ ou /ɛ/ — pas assez ouvert',
  },
  'ʌ': {
    label: 'A central (cup)',
    tipFr: 'Voyelle centrale courte. Bouche légèrement ouverte, langue au centre.',
    example: 'cup, but, love, blood',
    commonError: 'Confondu avec /a/ ou /ɔ/ par les francophones',
  },
  'ɪ': {
    label: 'I court (ship)',
    tipFr: 'Voyelle courte et détendue. Moins tendu que /i/ français.',
    example: 'ship, bit, sit, live',
    commonError: 'Prononcé trop long comme /iː/ français',
  },
  'iː': {
    label: 'I long (sheep)',
    tipFr: 'Voyelle longue et tendue. Lèvres étirées en sourire.',
    example: 'sheep, beat, sea, feel',
    commonError: 'Pas assez long ni tendu',
  },
  'ʊ': {
    label: 'OU court (pull)',
    tipFr: 'Voyelle courte et détendue. Lèvres légèrement arrondies.',
    example: 'pull, foot, look, good',
    commonError: 'Confondu avec /uː/ — trop long',
  },
  'uː': {
    label: 'OU long (pool)',
    tipFr: 'Voyelle longue. Lèvres très arrondies et projetées vers l\'avant.',
    example: 'pool, food, blue, moon',
    commonError: 'Pas assez long ni arrondi',
  },
  'ɹ': {
    label: 'R anglais (red)',
    tipFr: 'Langue relevée vers l\'arrière sans toucher le palais. Jamais roulé comme le R français.',
    example: 'red, right, three, very',
    commonError: 'Roulé à la française ou prononcé comme /w/',
  },
  'v': {
    label: 'V anglais (very)',
    tipFr: 'Lèvre inférieure légèrement sur les dents du haut. Son voisé.',
    example: 'very, vine, live, five',
    commonError: 'Confondu avec /w/ — "wine" prononcé "vine" ou vice-versa',
  },
  'w': {
    label: 'W (wine)',
    tipFr: 'Lèvres très arrondies puis qui s\'ouvrent rapidement. Jamais de contact dents-lèvre.',
    example: 'wine, water, when, queen',
    commonError: 'Prononcé comme /v/ — erreur très fréquente chez les francophones',
  },
  'h': {
    label: 'H aspiré (hello)',
    tipFr: 'Souffle d\'air depuis la gorge. En anglais le H est toujours prononcé (sauf exceptions).',
    example: 'hello, hat, house, who',
    commonError: 'H muet comme en français — non prononcé',
  },
  'ŋ': {
    label: 'NG (sing)',
    tipFr: 'Nasale vélaire — langue contre le voile du palais. Pas de /g/ final.',
    example: 'sing, ring, king, long',
    commonError: 'Ajout d\'un /g/ final : "sing-guh"',
  },
  'dʒ': {
    label: 'DG (judge)',
    tipFr: 'Consonne affriquée. Comme /d/ suivi de /ʒ/ rapidement.',
    example: 'judge, jump, bridge, age',
    commonError: 'Prononcé simplement comme /ʒ/ (je)',
  },
  'tʃ': {
    label: 'TCH (church)',
    tipFr: 'Consonne affriquée. Comme /t/ suivi de /ʃ/ rapidement.',
    example: 'church, teach, cheese, much',
    commonError: 'Prononcé comme /ʃ/ seul',
  },
  'eɪ': {
    label: 'Diphtongue AY (face)',
    tipFr: 'Commence sur /e/ et glisse vers /ɪ/. Ne pas prononcer simplement /e/.',
    example: 'face, day, name, make',
    commonError: 'Prononcé comme le /e/ français sans la glisse',
  },
  'oʊ': {
    label: 'Diphtongue OW (go)',
    tipFr: 'Commence sur /o/ et glisse vers /ʊ/. Ne pas prononcer simplement /o/.',
    example: 'go, home, phone, boat',
    commonError: 'Prononcé comme le /o/ français sans la glisse',
  },
  'aɪ': {
    label: 'Diphtongue AI (price)',
    tipFr: 'Commence sur /a/ ouvert et glisse vers /ɪ/.',
    example: 'price, time, like, my',
    commonError: 'Prononcé comme /aj/ français — acceptable mais peut sonner étranger',
  },
  'aʊ': {
    label: 'Diphtongue AOU (mouth)',
    tipFr: 'Commence sur /a/ ouvert et glisse vers /ʊ/.',
    example: 'mouth, now, house, out',
    commonError: 'Prononcé comme /ao/ avec deux syllabes',
  },
};
